export const limitedFragmentList = [
  "Artistry",
  "Awakening",
  "Care",
  "Caution",
  "Compassion",
  "Desperation",
  "Ferocity",
  "History",
  "Ingenuity",
  "Inspiration",
  "Moonlight",
  "Preparation",
  "Rage",
  "Resolve",
  "Skill",
  "Support",
  "Tenacity",
  "Violence",
];

export const limitedActionList = [
  "Essence of the Aetherweaver",
  "Essence of the Breathtaker",
  "Essence of the Guardian",
  "Essence of the Irregular",
  "Essence of the Martialist",
  "Essence of the Ordained",
  "Essence of the Platebearer",
  "Essence of the Profane",
  "Essence of the Savior",
  "Essence of the Skirmisher",
  "Essence of the Veteran",
  "Essence of the Watcher",
  "Light Curtain",
  "Lodestone",
  "Lost Arise",
  "Lost Assassination",
  "Lost Banish III",
  "Lost Bravery",
  "Lost Bubble",
  "Lost Burst",
  "Lost Chainspell",
  "Lost Cure",
  "Lost Cure II",
  "Lost Cure III",
  "Lost Cure IV",
  "Lost Death",
  "Lost Dispel",
  "Lost Focus",
  "Lost Incense",
  "Lost Impetus",
  "Lost Manawall",
  "Lost Paralyze III",
  "Lost Protect",
  "Lost Protect II",
  "Lost Rampage",
  "Lost Reflect",
  "Lost Shell",
  "Lost Shell II",
  "Lost Slash",
  "Lost Spellforge",
  "Lost Stealth",
  "Lost Steelsting",
  "Lost Stoneskin",
  "Lost Stoneskin II",
  "Lost Swift",
  "Resistance Ether Kit",
  "Resistance Medikit",
  "Resistance Phoenix",
  "Resistance Potion",
  "Resistance Potion Kit",
  "Resistance Reraiser",
];